### ISSUE TITLE
Does it support editing smart layers?

### ISSUE THREAD

**Issue by lanadeldel** [webtoon/psd#2]

**Comment by dlehdanakf** [comment]
We currently do not support smart layers, neither editing.

**Comment by pastelmind** [comment]
Hi, @lanadeldel! If you're referring to Smart Objects, we don't support parsing layer effects yet, though quick testing indicates we can decode the image of a Smart Object layer just fine.

If you would like to request a feature, feel free to expand upon the issue here! We'd also be happy to accept a PR.

**Comment by maoweifan** [comment]
I think I need that function too, dynamically replace the image in the smart layer, then export as png|jpeg
